### ISSUE TITLE
Enums are not case insensitive

### ISSUE THREAD

**Issue by vmelamed** [commandlineparser/commandline#198] opened 2017-12-06 17:46 UTC
First off: great job, guys!

Small issue: it looks like even though the wiki states that option properties bound to enum values are case insensitive:

> When specifying enum values, you don't need to respect case. Both app -g bye and app --greet-type REGARDS are allowed.

unfortunately, they are not. I have a program that for a line like this:
```
settings -s gogo -v 23 -t int
```
where -t is bound to an  `enum SettingType {Int, String, ...}`, I get an error:
```
ERROR(S):
  Option 't, type' is defined with a bad format.

  -s, --setting      The name of a setting to be added or modified.

  -v, --value        The new value of the setting. The option is required if -s or --setting is specified.

  -t, --type         (Default: String) The case-sensitive type of the value of the setting. The option is not mandatory and if not specified, the
                     type will be either implied from the existing setting with the same name or it will be assumed to be 'String'. The most common
                     types are: String, Int, Guid, Decimal, Boolean, DateTime, Date, Time, Uri, TimeSpan. DateTime values are assumed to be UTC.

[...etc]

BadFormatConversionError
  StopsProcessing          = False
  Tag                      = ErrorType.BadFormatConversionError
  NameInfo                 = NameInfo
    LongName                 = type
    NameText                 = t, type
    ShortName                = t
```

But if I enter the command like this:
```
settings -s gogo -v 23 -t Int
```
all is good.

**Comment by nemec** [comment] 2017-12-06 19:07
If you configure your own parser settings you can set `CaseInsensitiveEnumValues` to `true` - does that solve your problem?

    var parser = new Parser(with => with.CaseInsensitiveEnumValues = true);

**Comment by vmelamed** [comment] 2017-12-08 02:17
This didn't seem to have any effect. Maybe I'm doing it wrong but...

**Comment by mscrivo** [comment] 2018-01-08 21:21
Same issue here, CaseInsensitiveEnumValues has no effect

**Comment by harlam357** [comment] 2018-01-09 14:15
Also experiencing the same issue using the latest v2.2.0 package.  Setting CaseInsensitiveEnumValues = true has no effect.

**Comment by mdesousa** [comment] 2018-01-25 13:46
Also, I just upgraded from version 1.9.71 where CaseInsensitiveEnumValues used to be true by default. It appears that the new version (2.2.1) changes the default to be false... is this intentional? I think it would be more convenient to continue having the same default behavior as before.

**Comment by mleenhardt** [comment] 2018-03-19 00:29
I'm running into the same issue, any chance the fix contained #231 could be merged?

**Comment by mleenhardt** [comment] 2018-03-19 00:33
I'm running into the same issue, any chance the fix in #231 could be merged?

**Comment by Sergio0694** [comment] 2018-06-01 16:22
Same here with version **2.2.1**, the `CaseInsensitiveEnumValues` option doesn't work.
Looking forward to the next update with the fix 😊

**Comment by nemec** [comment] 2018-06-01 18:16
Can you provide a code sample that isn't working for you? I just tested the following in 2.2.1 and the case insensitive setting works as advertised.

```csharp
void Main()
{
	var parser = new Parser(cfg => cfg.CaseInsensitiveEnumValues = true);
	var results = parser.ParseArguments<Options>("-t two".Split())
		.WithParsed<Options>(opts => opts.Dump())
		.WithNotParsed<Options>((errs) => { });
}

public class Options
{
	[Option('t', "test")]
	public Test Test { get; set; }
}

public enum Test
{
	One,
	TWO
}
```

**Comment by Sergio0694** [comment] 2018-06-01 22:05
@nemec Hello, thank you for your answer. I can confirm that the issue is still present, and that it is only happening when using the `ParseArguments<T1, T2, …>()` overload. Using the method with a single type parameter works fine for me, both using an option and using a verb.

Consider this example:

```csharp
public enum SomeEnum
{
    Hello,
    World
}

public class SomeOptions
{
    [Option('f')]
    public SomeEnum Foo { get; set; }
}

[Verb("verb")]
public class SomeVerb : SomeOptions { }

[Verb("otherverb")]
public class SomeOtherVerb : SomeOptions { }
```

The following snippet fails with a "BadFormatConversionError" error:

```csharp
var test = new[] { "verb", "-f", "world" };
var parser = new Parser(settings => settings.CaseInsensitiveEnumValues = true);
var result = parser.ParseArguments<SomeVerb, SomeOtherVerb>(test);
```

Hope this helps! 😄

**Comment by masters3d** [comment] 2018-06-07 21:14
Having the same issue as @Sergio0694 . I think the default should be set to true.

**Comment by giuliov** [comment] 2018-07-18 20:18
It would be nice if you merge this PR after so many months.

**Closed as completed** 2018-08-13 22:42 UTC
Labels: bug

**Comment by fayssalm** [comment] 2018-10-17 15:05
still having the same issue as of 2.3.0

**Comment by o4zloiroman** [comment] 2020-04-24 13:12
Yeah, it's still not explained on wiki that the default value for this setting is actually false.
