### ISSUE TITLE
Since 2.4.0 do not support .NETFramework 4.5.2

### ISSUE THREAD

**Issue by smorzhov** [commandlineparser/commandline#407] opened 2019-02-01 10:54 UTC
Trying to install the latest version via Nuget got the following error. However, version 2.3.0 was installed successfully.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'CommandLineParser 2.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
```

**Comment by wischi-chr** [comment] 2019-02-02 13:40
That is also true for .NET 4.0 which should be compatible according to the readme - it that still the case?

Edit: Maybe this issue should be closed, looks like a duplicate of #388

**Comment by ericnewton76** [comment] 2019-02-02 14:02
Also a duplicate of #387

We have a fix coming.

**Comment by ooples** [comment] 2019-03-01 01:09
I'm also needing a fix for this issue because I use .net 4.5.2

**Comment by moh-hassan** [comment] 2019-05-06 12:52
This issue is resolved in the release [2.5.0](https://www.nuget.org/packages/CommandLineParser/2.5.0)

**Closed as completed** 2019-10-02 16:24 UTC
