### ISSUE TITLE
Custom validation or error message during Options parsing

### ISSUE THREAD

**Issue by eho-impetus** [commandlineparser/commandline#360] opened 2018-11-06 11:14 UTC
Let's say I have the following Options (command line arguments):
```C#
public class Options
{
      [Option("major", Required = true, HelpText = "Major version number. Must be int or {Function}.")]
      public string Major { get; set; }

      [Option("minor", Required = true, HelpText = "Minor version number. Must be int or {Function}.")]
      public string Minor { get; set; }

      [Option("build", Required = true, HelpText = "Build version number. Must be int or {Function}.")]
      public string Build { get; set; }

      [Option("revision", Required = true, HelpText = "Revision version number. Must be int or {Function}.")]
      public string Revision { get; set; }
}
```
User may provide following arguments...
```MyTool.exe --major 3 -- minor 5 -- build {YearShort} -- revision {DayOfYear}```
... to receive a generated version number: 3.5.18.310
So the type for my Options is either an int or an enum.

### Question
Is there any way to be called back during argument parsing, custom validate an argument value and provide a custom error text in case argument has invalid values?
Example for invalid use:
```MyTool.exe --major 3 -- minor abc -- build {YearXShort} -- revision {AnyNotImplementedFunction}```

**Comment by ohadschn** [comment] 2019-08-21 15:04
Looks like a dupe of https://github.com/commandlineparser/commandline/issues/146

**Comment by moh-hassan** [comment] 2020-01-09 22:29
Duplication of #146

**Closed as completed by moh-hassan** 2020-01-09 22:29 UTC
