### ISSUE TITLE
Multiple input parameters

### ISSUE THREAD

**Issue by HolyOne** [commandlineparser/commandline#522] opened 2019-10-14 09:02 UTC
Does commandline support multiple input parameters such as?

combine.exe -i file1.txt -i file2.txt -i file3.txt -o all.txt

I can do this with IEnumerable and Seperator parameter of Option Attribute but I need multiple options with same name.

**Comment by moh-hassan** [comment] 2019-10-17 23:31
No,  it doesn't support multiple input parameters with the same name.
It's planned to add this feature.

**Comment by josesimoes** [comment] 2019-12-05 14:39
I believe this is a duplicate of #357...

**Comment by rmunn** [comment] 2020-03-13 09:28
PR #594 would implement this feature; most of the work was done by @tydunkel, I just rebased his work onto the current state of the `develop` branch and created the PR.

**Comment by josesimoes** [comment] 2020-03-13 10:06
Awesome!! Thank you!! 👏 🎉 😃

**Closed as completed** 2020-07-06 21:24 UTC
Labels: enhancement
