### ISSUE TITLE
Using Double Quotation for two seperate fields issue  

### ISSUE THREAD

**Issue by GuyDayannn** [commandlineparser/commandline#875] opened 2023-02-16 11:57 UTC
Hi,
My first time posting an issue (so please forgive me for my mistakes).

I'm getting a parsing error when trying to do the following 
`run --id 11 --n "Guy" --d database --t "Transfer 1"`

It seems the using of double quotation (on --n and --t) in two different parameters may caused this issue becuase the following did work:
`transfer run --id 11 --n Guy --d database --t "Transfer 1" `

I'm using 
`CommandLine.Parser.Default.ParseArguments<TransferOptions>(args)
                    .MapResult(
                        (TransferOptions transferOptions) => RunTransfer(transferOptions),
                        _ => new NotFoundCommand()`

and notParsedFunc was called.

**Comment by elgonzo** [comment] 2023-02-16 12:16
I cannot reproduce. What precisely is the contents of the `args` string array, and where do the values of that specific _args_ string array you are using are coming from (is it the _args_ parameter of the _Main_ method, or something else)?

As you did not explain the nature of the error you got (aside from just a quite vague mention of some "notParsedFunc" being called...), it's hard to tell what the problem here is, but i tend to suspect that the _args_ string array you are passing to _ParseArguments_ is not the original unmodified _args_ string array provided to the _Main_ method...

When a parsing error occurs, an _IEnumerable\<Error\>_ is being passed to notParsedFunc. However, you discard it (due to using `_ => ...` as notParsedFunc). If you don't see any error message being printed in the console by the parser, try inspecting and/or dumping the content of the _IEnumerable\<Error\>_ that's being passed to notParsedFunc...

**Comment by GuyDayannn** [comment] 2023-02-16 12:55
Thanks for the help!
It seems like I have a problmetic regex.

**Comment by elgonzo** [comment] 2023-02-16 12:58
> It seems like I have a problmetic regex.

Alright. If the issue has been identified to be not caused by the CommandLineParser library, it would be kind if you would close this issue here. You as the author of the issue report should see a "Close" button at the bottom of this issue thread for closing the issue. Thanks!

**Comment by GuyDayannn** [comment] 2023-02-16 13:18
Ok.
Thank you very much for the help.

**Closed as completed** 2023-02-16 13:18 UTC
