### ISSUE TITLE
AssemblyTitle cut off at period in help output

### ISSUE THREAD

**Issue by Calteo** [commandlineparser/commandline#326] opened 2018-09-12 20:22 UTC
When the AssemblyTitle attribute contains a period (i.e. "Some.Text") then only the first part is printed in the help output (i.e. "Some 1.2.3.4").

**Comment by nemec** [comment] 2018-09-13 03:05
Duplicate of #312, fixed in develop branch

**Closed as completed by nemec** 2018-09-13 03:05 UTC
