### ISSUE TITLE
Bug:  option as string with length one char raise error in v2.3 but working fine in v1.9.71

### ISSUE THREAD

**Issue by moh-hassan** [commandlineparser/commandline#319] opened 2018-08-31 20:35 UTC
The following option raises an exception  in CommandLineParser v2.3 :

>Run-time exception : Long name should be longest than one character.  
Check [the demo ](https://dotnetfiddle.net/4gSibD)
		
	public  class Options
        {
		
		
            [Option("i", HelpText = "If file has errors don't stop processing.")] 
            public bool IgnoreErrors { get; set; }
			
	}
		
But it's working fine in v 1.9.71  
Check  [the demo ](https://dotnetfiddle.net/ECOTVn)
		
I find that option "i" as  string, or 'i' as  char is working fine in v1.9.71, 
but "i" as  string isn't working and raise exception in v2.3  
 
It seems that in v2.3 option shortName and longName should exist (not shortName only) like:

             [Option('i, "Ignore", HelpText = "If file has errors don't stop processing.")] 
            public bool IgnoreErrors { get; set; }

**Comment by nemec** [comment] 2018-08-31 20:45
This is expected behavior to eliminate the ambiguity of users not knowing whether to set the option with one or two dashes for single-character options (e.g. `-i` vs `--i`). If it's a single character option it _must_ be surrounded by single quotes and a multi-character option _must_ be surrounded by double quotes (the compiler catches this one, of course).

I did not realize it "worked" in previous versions, but it was a bug that is apparently now fixed.

P.S. thank you for the illustrative demos, they are very much appreciated when diagnosing an issue :)

**Comment by moh-hassan** [comment] 2018-08-31 20:51
But, in v2.3, both shortName and longName should exist (not shortName only) 
check  the comments in  [the demo](https://dotnetfiddle.net/4gSibD)
Is't right?

**Comment by nemec** [comment] 2018-08-31 21:03
Can you clarify what the issue is? As you noted, the following is both the correct way to implement it, and it works if I paste that code into your fiddle.

```csharp
[Option('i',"ignore", HelpText = "If file has errors don't stop processing.")]
public bool IgnoreErrors { get; set; }
```

**Comment by moh-hassan** [comment] 2018-08-31 21:16
Just, i want to insure that the correct way  to use of option in v2.3 is providing both shortName and longName  as you described ( that is fine, and i agree :) )

 Providing one shortName or longName pass compilation but raise run-time error. ( and should be avoided,  and i agree)

Thanks for help. You can close the issue.

**Comment by nemec** [comment] 2018-08-31 21:26
Okay, I hope you enjoy the library!

**Closed as completed by nemec** 2018-08-31 21:26 UTC
